//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public price()
        {
            this.vendings = new HashSet<vending>();
        }
    
        public int priceId { get; set; }
        public Nullable<int> sodaId { get; set; }
        public double price1 { get; set; }
    
        public virtual soda soda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vending> vendings { get; set; }
    }
}
