//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendingMachine.Infrastructure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendingMachineContext : DbContext
    {
        public VendingMachineContext()
            : base("name=VendingMachineContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<price> prices { get; set; }
        public virtual DbSet<quantity> quantities { get; set; }
        public virtual DbSet<soda> sodas { get; set; }
        public virtual DbSet<vending> vendings { get; set; }
        public virtual DbSet<vendingTable> vendingTables { get; set; }
    }
}
